---
- name: Uninstall Playbook of a AMQ Standalone Environment
  
  # uninstall
  hosts: master:slave
  connection: local

  serial: 1  
  remote_user: "{{ vault_os_amq.remote_user }}"
  gather_facts: true
  become: yes
  become_user: "{{ vault_os_amq.become_user }}"
  become_method: su
  roles:
    - { role: amq-uninstall }
