---
- name: AMQ Master/Slave Playbook
  
  # install
  hosts: master:slave
  connection: local
  
  serial: 1
  remote_user: "{{ vault_os_amq.remote_user }}"
  gather_facts: true
  become: yes
  become_user: "{{ vault_os_amq.become_user }}"
  become_method: su
  
  # Set capabilities to install
  vars:
    role_install_broker: true
    role_install_interconnect: false
  
  roles: 
    - {
        role: amq-install,
        amq_name: 'amq01',
        port_offset: '0',
        nob: 'false',
        amq_master_slave: 'true'
      }
