---
- name: Uninstall Playbook of a AMQ Standalone Environment
  
  # uninstall
  hosts: master:slave
  connection: local

  serial: 1  
  remote_user: "{{ lookup('env','USER') }}"
  gather_facts: true
  
  # User that will install AMQ in remote machine
  become: yes
  become_user: "{{ vault_os_amq.become_user }}"
  become_method: sudo
  
  roles:
    - { role: amq-uninstall }
