---
#- name: Check if Fuse Service Exists
#  stat:
#    path: /etc/systemd/system/fuse-{{ esb_name }}.service
#  register: 'fuse_{{ esb_name | replace("-", "_") }}_service_status'

#- name: Stop Fuse Service
#  service:
#    name: fuse-{{ esb_name }}
#    state: stopped
#  when: 'fuse_{{ esb_name | replace("-", "_") }}_service_status.stat.exists'

#- name: Uninstall systemd unit file
#  file:
#    path: /etc/systemd/system/fuse-{{ esb_name }}.service
#    owner: root
#    state: absent
#  when: 'fuse_{{ esb_name | replace("-", "_") }}_service_status.stat.exists'
#  notify:
#    - reload systemd



#- name: Stop AMQ Service
#  shell: "{{ fuse_home }}/bin/stop"
#  environment:
#    BASH_ENV: "~/.profile"
#  args:
#    executable: "/bin/bash"
#    warn: no
#  become: yes
#  become_user: fuse

- name: Check whether AMQ instances exists
  stat:
    path: '{{ amq_broker_dir }}/{{ amq_broker_name }}/bin'
  register: amq_broker_dir_stat
  
- name: Stop AMQ Service
  shell: "{{ amq_broker_dir }}/{{ amq_broker_name }}/bin/artemis-service stop"
  environment:
    BASH_ENV: "~/.profile"
  args:
    executable: "/bin/bash"
    warn: no
  when: amq_broker_dir_stat.stat.exists

- name: Remove current instance
  file:
    path: '{{ amq_broker_dir }}/{{ amq_broker_name }}'
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent

## Check whether all instances are already uninstalled
- name: Check if a dir is empty
  find:
    paths: '{{ amq_broker_dir }}'
    file_type: directory
    patterns: '*'
  register: foundElements

- name: Remove instances directory
  file:
    path: '{{ amq_broker_dir }}'
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent
  when: foundElements.matched == 0

- name: Uninstall AMQ core
  file:
    path: "{{ amq_core_dir }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent
  when: foundElements.matched == 0

## DELETE CONTENT OF DATA
- name: Uninstall AMQ - collecting data internal files and directories
  find: 
    paths: "{{ amq_broker_data_dir }}"
    file_type: directory
    patterns: '*'
  register: data_directories_to_delete
  
- name: print data find_result
  debug: var=data_directories_to_delete  
  
- name: Uninstall AMQ - deleting data internal files and directories
  file: 
    path: "{{ item.path }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent
  with_items: "{{ data_directories_to_delete.files }}"    
       
    
## DELETE CONTENT LOG    
- name: Uninstall AMQ - collecting log internal files and directories
  find: 
    paths: "{{ amq_broker_log_dir }}"
    file_type: directory
    patterns: '*'
  register: log_directories_to_delete
  
- name: print log find_result
  debug: var=log_directories_to_delete  
  
- name: Uninstall AMQ - deleting log internal files and directories
  file: 
    path: "{{ item.path }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent
  with_items: "{{ log_directories_to_delete.files }}"   