---
- name: Remove current instance
  file:
    path: '{{ amq_broker_dir }}/{{ amq_broker_name }}'
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent

## Check whether all instances are already uninstalled
- name: Check if a dir is empty
  find:
    paths: '{{ amq_broker_dir }}'
    file_type: directory
    patterns: '*'
  register: foundElements

- name: Remove instances directory
  file:
    path: '{{ amq_broker_dir }}'
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent
  when: foundElements.matched == 0

- name: Uninstall AMQ core
  file:
    path: "{{ amq_core_dir }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent
  when: foundElements.matched == 0

## DELETE CONTENT OF DATA
- name: Uninstall AMQ - collecting data internal files and directories
  find: 
    paths: "{{ amq_broker_data_dir }}"
    file_type: directory
    patterns: '*'
  register: data_directories_to_delete
  when: delete_data_content
  
- name: print data find_result
  debug: var=data_directories_to_delete  
  
- name: Uninstall AMQ - deleting data internal files and directories
  file: 
    path: "{{ item.path }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent
  with_items: "{{ data_directories_to_delete.files }}"    
  when: delete_data_content
    
## DELETE CONTENT LOG    
- name: Uninstall AMQ - collecting log internal files and directories
  find: 
    paths: "{{ amq_broker_log_dir }}"
    file_type: file
    patterns: '*'
  register: log_directories_to_delete
  when: delete_log_content
  
- name: print log find_result
  debug: var=log_directories_to_delete  
  
- name: Uninstall AMQ - deleting log internal files and directories
  file: 
    path: "{{ item.path }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: absent
  with_items: "{{ log_directories_to_delete.files }}"  
  when: delete_log_content