---
# Delete configuration
- name: configure - memory - additional memory settings.
  xml:
    path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
    xpath: /conf:configuration/core:core/core:global-max-size
    state: absent
    namespaces: 
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes
  when: global_max_size_on_update
  
# Add configuration
- name: configure - memory - additional memory settings.
  xml:
    path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
    xpath: /conf:configuration/core:core/core:global-max-size
    value: "{{ global_max_size|string }}"
    namespaces: 
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes
  when: global_max_size_on_update