---

- name: configure - clustering - ensure shared storage directory exists
  file:
    path: "{{ amq_broker_data_dir }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    state: directory

